### ISSUE TITLE
Sistema de Continuous Integration

### ISSUE THREAD

**Issue by suissa** [NodeJS-Brasil/brazi.la#10]
Galera olha que sistema de CI bom feito em Node.js acho que podemos usar
https://github.com/Strider-CD/strider

**Comment by chrisenytc** [comment]
Que massa. Tem o https://travis-ci.org também..

**Comment by oswaldoacauan** [comment]
O bom do travis é que da pra integrar facim com o Github :dancer:

**Comment by chrisenytc** [comment]
É sim. Eu uso ele em alguns projetos. Travis é um dos mais usados para projetos Open-source, principalmente no GitHub.

**Comment by gustavohenke** [comment]
O [BrowserSwarm](http://browserswarm.com) parece que utiliza o Strider por debaixo dos panos.
É de se considerar se testes E2E estiverem em pauta... não sei qual é o suporte do Travis (minha preferência!) pra subir diversos browsers e testá-los.

**Comment by suissa** [comment]
Vocês que sabem, o que preferem?

**Comment by gustavohenke** [comment]
Eu voto pelo Travis + SauceLabs pra testes client :)

**Comment by chrisenytc** [comment]
:+1: Travis

**Comment by oswaldoacauan** [comment]
:+1: Travis

**Comment by alexsandro-xpt** [comment]
Travis tambem!

**Comment by suissa** [comment]
Travis então.
