### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oswaldoacauan** [NodeJS-Brasil/brazi.la#13]
Qual será licença que iremos distribuir o projeto?

Meu voto é para [MIT](http://opensource.org/licenses/MIT) ou [BEERWARE](http://en.wikipedia.org/wiki/Beerware) :beers:

**Comment by chrisenytc** [comment]
:+1: MIT

**Comment by luanmuniz** [comment]
MIT ou GPLv3 :+1:

**Comment by gustavohenke** [comment]
+1 MIT

**Comment by robotlolita** [comment]
MIT.

**Comment by suissa** [comment]
Gostei desse BEERWARE hein! :facepunch:

**Comment by danieltartarottisobrosa** [comment]
Voto pelo BEERWARE! :beer: :beers:

**Comment by luanmuniz** [comment]
Na mesma linha da BEERWARE temos também a [WTFPL](http://www.wtfpl.net/about/)

**Comment by suissa** [comment]
MIT ainda ta ganhando :(

**Comment by fdaciuk** [comment]
MIT :+1:

**Comment by brunosalgueiro** [comment]
Nunca entendi o real motivo de usar licença para Software Livre, alguém tem bons argumentos para usar?

**Comment by mateusavila** [comment]
Evitar que um filho da puta roube o código e comercialize como se fosse seu, e não da comunidade.

**Comment by mateusavila** [comment]
+1 MIT

**Comment by brunosalgueiro** [comment]
Isso evita que alguém faça uma patente de código proprietário? Pois pelo que pesquisei alguém pode alterar a licença para atender suas necessidades de projeto

**Comment by fdaciuk** [comment]
Pois é.. no caso da MIT pode mesmo. Talvez usar a GPLv3, que não deixa mudar a licença do software.

**Comment by luanmuniz** [comment]
Acho que pelo tempo aqui, ninguém mais vai se pronunciar. Acho que MIT ganhou!

**Comment by chrisenytc** [comment]
\O/ MIT

**Comment by luanmuniz** [comment]
Pelo tempo acho que MIT foi decidido!
Caso alguém tenha algum bom argumento para trocar a licença, abra outro Issue.
