### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by gustavohenke** [NodeJS-Brasil/brazi.la#18]
Como este é um projeto open source, e provavelmente terá interação de muita gente, acho válido forçar um code style.

Preferencialmente usando o [jscs](https://github.com/mdevils/node-jscs) via [Grunt](https://github.com/gustavohenke/grunt-jscs-checker) + arquivo `.editorconfig`.

**Comment by luanmuniz** [comment]
Tudo isso já deveria estar ai. Estranho.
Vou fazer o Push novamente o_O

**Comment by luanmuniz** [comment]
Pronto :)
Eu uso o Jshint, não conhecia esse jscs, então estou usando o jshint mesmo.
Fique a vontade para enviar um PR com qualquer modificação, caso ache necessário :D

**Comment by gustavohenke** [comment]
O JSCS é complementar ao JSHint. Ele valida estilo de código JS, já o JSHint valida boas práticas em JS.
Inclusive é utilizado pela equipe do jQuery em seus projetos principais (jQuery e jQuery UI).

Depois posso fazer um PR, basta só termos bem definido que convenções usar.

**Comment by luanmuniz** [comment]
Faça um PR com o que você acha legal, usa como base o que já tem hoje. Se tiver algo que alguem não concorde abrimos um discussão no PR :)
