### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by fdaciuk** [NodeJS-Brasil/brazi.la#29]
Dae galera! Sei que por enquanto tem pouca gente colaborando, mas acho que seria o momento de definirmos um styleguide para o projeto. Além do `.editorconfig`, para manter as coisas consistentes, seria legal criarmos (ou usarmos algum existente) padrão para codificação. 

Sugiro o que a equipe do jQuery usa: http://contribute.jquery.org/style-guide/js/

O que acham?

**Comment by gustavohenke** [comment]
Veja #23

O [JSCS](https://github.com/mdevils/node-jscs) tem (e a sua task [`grunt-jscs-checker`](https://github.com/gustavohenke/grunt-jscs-checker) também, a partir da `v0.3.0`) code styles built-in, e um deles é o jQuery.

É tão simples quando fazer usar essa task no Gruntfile:

``` javascript
jscs: {
    all: {
        options: {
            preset: "jquery"
        },
        src: [ ... ]
    }
}
```

**Comment by fdaciuk** [comment]
Show @gustavohenke! Não tinha visto a task =/
