### ISSUE TITLE
Vamos trabalhar com um algum gerador?

### ISSUE THREAD

**Issue by weblancaster** [NodeJS-Brasil/brazi.la#3]
Podemos gerar o projeto com yeoman ou apenas grunt.js.
Ou outros por ai.

**Comment by gnuwilliam** [comment]
Eu iria apenas pelo grunt, o yeoman coloca muita coisa, e as vezes me sinto fora do controle.. no grunt vc tem controle total. O que acham?

**Comment by fdaciuk** [comment]
+1 para o Grunt. Até porque futuramente podemos fazer um gerador do Yeoman para o braz.io xD

**Comment by luanmuniz** [comment]
Como gerenciador de tarefas para automatização do dev acho que o Grunt é sem dúvida o escolhido, mas ele não "gera" projeto. Antes de escolher um gerador (se é que teremos um), temos que saber como será a estrutura do projeto, porque dependendo da estrutura, nenhum gerador vai atender 100%. Sem contar que a principio usaríamos "MEAN" e um dos componentes dele é o Express que é um framework e que já geraria o projeto inicial.

A proposito, fazer um gerador do Yeoman para o braz.io :+1:

**Comment by gnuwilliam** [comment]
+1 pro generator do braz.io no Yeoman.

**Comment by matheuslc** [comment]
Grunt com certeza, e futuramente podemos criar um gerador para o braz.io, seria mais um ponto para agilizar o desenvolvimento.

**Comment by oswaldoacauan** [comment]
100% Grunt.

Pode-se pensar em fazer um gerador no Yeoman mais para frente, integrando o core com alguns plugins opcionais e um theme padrao :D

**Comment by weblancaster** [comment]
Sim concordo com Grunt.js também.. e @luanmuniz Grunt.js gera projeto sim é chamado de scaffolding.. O yeoman usa grunt para isso..

Aqui esta o link para mais informacoes http://gruntjs.com/project-scaffolding

**Comment by chrisenytc** [comment]
Seria interessante criar um Generator para Yeoman quando tive-se a primeira Release do projeto..

**Comment by suissa** [comment]
Uai usamos os 2.

**Comment by marcoostan** [comment]
Concordo em utilizar apenas o Grunt e criar um Generator para Yeoman :)

**Comment by diogobeda** [comment]
Concordo com o @chrisenytc, de criar o generator quando tivermos a release (:

**Comment by gustavohenke** [comment]
Também apoio a ideia de Grunt + generator do Yeoman.

**Comment by fabiorogeriosj** [comment]
+1 Grunt
