### ISSUE TITLE
Editor de texto

### ISSUE THREAD

**Issue by luanmuniz** [NodeJS-Brasil/brazi.la#33]
Fala galera,

Daqui a pouco vou começar a desenvolver o editor de texto e queria a opinião de vocês!
Vocês acha melhor usar Markdown ou HTML normal?
Por favor, digam porque preferem um ao outro, defendam sua opinião!

**Comment by matheuslc** [comment]
Prefiro Markdown pelo fato de ser mais ágil e fácil. Além de que meio que tem se tornado um padrão.

**Comment by fdaciuk** [comment]
Bom, IMHO, acho que seria legal fazer algo que facilite pra pessoas leigas usarem. Dar a opção de escrever em MD com certeza, mas acho que deveria ser um WYSIWYG, como o TinyMCE por exemplo, que tem bastantes opções de personalização.

Ou talvez deixar como padrão MD e fazer o WYSIWYG como módulo, também seria bacana xD

**Comment by gustavohenke** [comment]
@fdaciuk Na verdade, acho que não tem o que você não faça com markdown, ainda mais se for o GFM. A não ser que você esteja falando de frescurites que 1% sabe/precisa usar. Além do mais, WYSIWYG gera mto código ruim e que dificulta SEO.

**Comment by fdaciuk** [comment]
@gustavohenke, o usuário leigo que comentei seria o cliente final. Imagina você desenvolvendo um projeto usando o Brazila como CMS, por exemplo. O cliente final não saberia adicionar conteúdo em Markdown. Por isso comentei sobre o WYSIWYG.

**Comment by caarlos0** [comment]
De qualquer modo, se tu escrever HTML dentro de um markdown ele compila normalmente :)

**Comment by gustavohenke** [comment]
@fdaciuk E que tal assim? http://hallojs.org/demo/markdown/ :)

@caarlos0 Não tudo. A engine do GFM remove classes, estilos inline, entre outros atributos, mas não sei dizer se só em elementos block ou todos.

**Comment by fdaciuk** [comment]
A questão nem é o HTML @caarlos0.. é mais ter uma interface com botões de bold, italic, align, etc.

@gustavohenke, é disso que eu tô falando `*___*`

**Comment by caarlos0** [comment]
@gustavohenke hmm, não sabia disso...

@fdaciuk sim, entendi essa parte... apenas tinha comentado a possibilidade de ~mesclar~ ambos.

**Comment by luanmuniz** [comment]
@gustavohenke Gostei desse demo em!! Acho que podemos adotar esse estilo ai!! \o/

**Comment by matheuslc** [comment]
Então, eu uso o Ghost, curto muito markdown e acho bem prático, mas é o que o @luanmuniz  disse, para um usuário leigo final fica difícil. Porém, se fosse um markdown com WYSIWG seria perfeito.

**Comment by fdaciuk** [comment]
Pode crer @caarlos0 xD

Também curti @luanmuniz xD

Vai ficar da hora essa parada o/

**Comment by fdaciuk** [comment]
Esses aqui também são bem legais: 
- http://sofish.github.io/pen/
- http://lab.lepture.com/editor/

Falta achar um que tenha opção de subir imagens agora xD

Ou fazer um módulo pra isso também, hahah! :P

**Comment by luanmuniz** [comment]
@fdaciuk Não vai ter um que sobe imagem, vamos ter que desenvolver hihihihih

**Comment by fabiorogeriosj** [comment]
Wow. Ta ficando interessante o projeto. É isso ae galera vamos unir o
conhecimento de cada e fazer algo show...
Em 21/01/2014 22:07, "Luan Muniz" notifications@github.com escreveu:

**Comment by fdaciuk** [comment]
#partiu então @luanmuniz o/

xD

**Comment by oswaldoacauan** [comment]
Não gosto da ideia de ter um TinyMCE da vida, muita tralha pra pouco uso.

Acho mais legar ser só markdown (visto que markdown aceita html puro) e com no máximo algo parecido com isso http://daviferreira.github.io/medium-editor/

Markdown é muiiito simples para precisar ser abstraido por um plugin tipo TinyMCE.

Edit.: @fdaciuk gostei pra caralheos do segundo, só tem o básico e escreve direto em markdown :D

**Comment by fdaciuk** [comment]
Sim @oswaldoacauan xD

O TinyMCE realmente é muito, mas pra cliente final precisa de algo assim.. mas esses exemplos ae acho que já estão de bom tamanho xD

**Comment by suissa** [comment]
@gustavohenke muito bom esse editor hein!
