### ISSUE TITLE
Design do painel administrativo

### ISSUE THREAD

**Issue by luanmuniz** [NodeJS-Brasil/brazi.la#34]
Fala galera,

Nosso amigo @fabiorogeriosj fez uma primeira versão para o design do admin!!
Deem feedback, marquem no layout as observação de vocês!

https://redpen.io/csmb4p

**Comment by caarlos0** [comment]
Sinceramente, ficou MUITO foda!

Parabéns @fabiorogeriosj, take this :beers:!

**Comment by gustavohenke** [comment]
gostei muito! ;)

**Comment by fabiorogeriosj** [comment]
Valew @caarlos0, @gustavohenke e @matheuslc!
@matheuslc Ficarei responsável pelo front-end dessa interface! Porem se tiver mais pessoas afim de contribuir sera bem vindo :)

**Comment by NandoKstroNet** [comment]
Rpz ta da hora, creio que quando implementado ficará melhor ainda. Vai ser responsivo?

**Comment by fabiorogeriosj** [comment]
Sim @NandoKstroNet, será responsivo!
Penso em utilizar vários recursos do HTML5 e CSS3 porem não podemos deixar de dar suporte aos malditos IE's antigos.

**Comment by matheuslc** [comment]
@fabiorogeriosj legal cara, gostaria de contribuir também. IE8+ né?

**Comment by fabiorogeriosj** [comment]
Show @matheuslc. Após definido o layout irei criar as issues do front-end, ai trocamos umas ideias.

Com relação ao IE acho que podemos sim dar suporte apenas IE8+. Mas isso pode ser discutido com a galera depois se realmente deixamos para traz o IE7-

**Comment by matheuslc** [comment]
@fabiorogeriosj Fechado então, vou acompanhando.

**Comment by suissa** [comment]
DO CARALEO me lembrou um mix de Ghost com G+ :+1:

**Comment by suissa** [comment]
IE8+

**Comment by suissa** [comment]
Bora fazer em Stylus neh ja q estamos trabalhando com Node.js

Rola fazer um atomic design fodido

**Comment by fdaciuk** [comment]
Só vi agora xD

Ficou muito bom mesmo! Parabéns @fabiorogeriosj!

**Comment by chrisenytc** [comment]
Ficou muito foda. Parabéns @fabiorogeriosj :+1:

**Comment by kassyuz** [comment]
Ficou bom cara, parabéns!

**Comment by fabiorogeriosj** [comment]
Valew @suissa @fdaciuk @chrisenytc @kassyuz!
Agora vou criar as outras telas para que vocês possam dar um feedback e se possível melhorar a interface, depois do ok da galera começo a implementa-la. 

E já adianto que gosto muito de usar efeitos visuais que agrega na interface mas é claro que não deixo isso ferrar a performance da mesma.

A ideia é essa @suissa, vamos fazer algo show de bola, da interface ao core :)

**Comment by suissa** [comment]
Já foram definidas as features que teremos? Para conseguir criar um mockup mais fiel.

**Comment by cyberglot** [comment]
estou terminando um fw (na verdade, é mais uma lib) em Stylus de UI, tipo o bootstrap. se vcs puderem/quiserem esperar um pouco mais para implementar (coisa de 1 semana ou um pouco mais). Será IE9+ com graceful degradation pro resto das porcarias.

**Comment by suissa** [comment]
DEMOROU!

**Comment by vitorbritto** [comment]
Está ficando show de bola! Parabéns @fabiorogeriosj!

Ia comentar sobre essa questão dos mockups e protótipos também. Vou aguardá-los com features do painel para dar uma opinião mais sólida. =]

**Comment by hugofcampos** [comment]
Eu gostei bastante!

**Comment by fabiorogeriosj** [comment]
Valew @vitorbritto e @hugofcampos.

deem uma olhada na ideia inicial da pagina de conteúdo. Lembrando galera que nesses mockups iniciais estou criando a identidade do brazila em relação ao estilo, isso não significa que serão esses dashboards que terá ou até mesmo que o editor será assim e tals, é apenas um exemplo.

https://redpen.io/uk9afg

Com relação as features concordo @suissa. Com isso fica mais fácil e preciso de fazer os mockups, lembrando que á ideia é seguir a risca (cores, posicionamento, tamanhos, etc) os mockups.

Quando podemos definir isso @luanmuniz?

**Comment by oswaldoacauan** [comment]
Parabens @fabiorogeriosj ficou show de bola o layout. Só achei alguns botões com pouco destaque, como o de "Create a new content", nao entendi o porque ele nao seguiu o padrão dos outros.

**Comment by weblancaster** [comment]
Ficou supimpa mesmo..

![giphy](https://f.cloud.github.com/assets/549394/1990838/93b31954-848c-11e3-8b5a-7c8135e49b78.gif)

**Comment by gustavodemari** [comment]
Excelente.
@fabiorogeriosj o que você usou para fazer o mockup?
Abs!

**Comment by luanmuniz** [comment]
@fabiorogeriosj Já tenho quase tudo anotado, te chamo aqui no chat e te passo isso certinho! \o/

**Comment by fabiorogeriosj** [comment]
Concordo @oswaldoacauan preciso melhorar o link de novo conteúdo.

Valew @weblancaster.
@gustavohenke  usei o Photoshop e conceitos de anos de trabalho duro hehehe.

No aguardo @luanmuniz...

Valew pelo feedback galera.
