### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by suissa** [NodeJS-Brasil/brazi.la#4]
Quem tem um modelo legal de README para colocarmos no repo?

**Comment by robotlolita** [comment]
Eu costumo usar:

``` markdown
Título
====

( badges de CI / etc)

Descrição do que o projeto é.

## Philosophy

( guidelines gerais do projeto )

## Example (no caso de bibliotecas)

## Installing

( npm install ...)

## Getting started / basic usage

## Documentation

## Tests

## Platform support

## Licence
```

Tem todas as informações que alguém poderia precisar aí. Os README's do ClojureWerkz são muito bons também: https://github.com/michaelklishin/welle

**Comment by luanmuniz** [comment]
Bom, a partir de agora, se alguém quiser propor alguma alteração no README.md que faça um PR :)
