### ISSUE TITLE
Issues Labels

### ISSUE THREAD

**Issue by luanmuniz** [NodeJS-Brasil/brazi.la#5]
Quais devem ser as labels dos Issue deste projeto?

**Comment by luanmuniz** [comment]
Eu uso em alguns projetos:
- New feature (Para requisições de novas funcionalidades)
- Awaiting feedback (Para qualquer coisa que esteja aguardando feedback)
- Bug (Para Bugs. obvio)
- Documentation (Para qualquer coisa relacionada a documentação)
- Performance problem (Para problemas de perfomance)

Acho que além dessas podemos usar
- New module request (Para sugestões de novos modulos)
- Design (Para qualquer coisa relacionada a design)
- Third Parts (Para problemas com dependências ou com partes de terceiros)

O que acham?

**Comment by chrisenytc** [comment]
Eu gostei.. Tem meu apoio.. :+1:

**Comment by nicholasess** [comment]
+1

**Comment by diogobeda** [comment]
+1

2013/10/1 Nicholas Eduardo notifications@github.com

> +1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NodeJS-Brasil/braz.io/issues/5#issuecomment-25424102
> .

## 

Diogo César.

**Comment by suissa** [comment]
+1

**Comment by oswaldoacauan** [comment]
Gostei mas eu sugiro uma estrutura um pouco diferente:

Categorias:
- Feature
- Enhancement
- Feedback
- Bug
- Documentation
- Design (não sei se é realmente necessario)
- Suggestion
- Question
- Discussion

Status:
- Pending
- Working

Acho legal a ideia de labels de prioridade
- High priority
- Medium priority
- Low priority

Acho que assim fica mais flexível :smile:

**Comment by caarlos0** [comment]
@luanmuniz eu adicionaria `Security Issue` na sua lista também :)

**Comment by luanmuniz** [comment]
@caarlos0 Boa!!

@oswaldoacauan Gostei da ideia de colocar Labels de Status.
Qual é a finalidade de cada categoria que você comentou?

**Comment by oswaldoacauan** [comment]
@luanmuniz Qual delas tu não entendeu? Achei todas auto-descritivas

**Comment by luanmuniz** [comment]
@oswaldoacauan Qual a diferente entre Feature e Enhancement? Entre Question, Suggestion e Discussion? Entre Suggestion e Enhancement?

**Comment by oswaldoacauan** [comment]
@luanmuniz 
Feature é uma nova funcionalidade.
Enhancement pode ser uma melhora em uma funcionalidade ou processo já existente.
Question é alguma pergunta feita por alguem da comunidade.
Suggestion é alguma sugestão feita por alguem da comunidade, que pode ser uma melhoria, uma nova feature.
Discussion é quando alguma Issue vira uma discussao (sadia), como essa que estamos agora.

**Comment by chrisenytc** [comment]
Muito bom @oswaldoacauan gostei :+1:

**Comment by luanmuniz** [comment]
@oswaldoacauan Acho que da pra juntar suggestion, enhancement e feature numa label só, tipo, "Melhoria" ou algo assim. (A propósito, temos que decidir, se trataremos tudo em inglês ou pt-br)
Tipo, para mim, toda issue é uma discussão, então me parece meio estranho ter uma label Discussion, tendo em vista que tudo se encaixa no contexto da label.
O que tu acha?

**Comment by chrisenytc** [comment]
@luanmuniz Acho que assim ficaria mais limpo e simples. E sobre o idioma seria interessante a base do projeto ser em inglês, as Labels também mais dar suporte a Issues em pt-br também, assim poderia dar suporte a milhares de pessoas no mundo que cheguem a conhecer o projeto mais sem forçar as pessoas daqui a precisar criar issues em inglês. Começar o projeto do pt-br e depois começar uma rotina de tradução até a primeira release também é uma opção.

**Comment by oswaldoacauan** [comment]
@luanmuniz @chrisenytc Discordo, ao meu ver TUDO deve ser tratado em inglês (depois de definirmos essa parte inicial do projeto) aqui no Github, assim qualquer um pode opinar ou entender sobre o que a issue se trata, se alguem tem alguma duvida em portugues pode tirar por outros meios (grupos no facebook, twitter, etc).

Sobre juntar Suggestion, Enhancement e Feature, tambem não gosto da ideia, são coisas totalmente diferentes, então não devem ser tratadas igualmente.

O label discussion é para os casos que se tem issues duplicadas e move-se todas para apenas uma issue de discussao, onde será definido x ou y.

**Comment by diogobeda** [comment]
Concordo com as Issues serem todas em inglês. Por mais que seja mais comodo pra quem é daqui tratar em pt-br e ir traduzindo, é bom que a gente se acostume a fazer tudo em inglês pois 99.99% (números não precisos :P) dos projetos open-source são em inglês. Isso fortalece a galera daqui deixando eles mais à vontade pra participar sem medo de outros projetos posteriormente.

**Comment by chrisenytc** [comment]
@oswaldoacauan É uma boa abordagem. Falei isso de dar suporte a pt-br por conta de outras pessoas. Eu só uso português quando é por obrigação. Todos os meus projetos e tudo que eu uso ou participo é em inglês. Usar apenas inglês tem meu apoio. :+1:

**Comment by fdaciuk** [comment]
Nesse caso eu concordo com o @luanmuniz. Acho que separar em muitas labels pode gerar mais bagunça. Deixando com menos categorização, fica mais fácil identificar do que se trata a issue.

Sobre as prioridades, poderíamos usar os milestones.

E sobre a questão do idioma, com certeza: EN. xD

**Comment by oswaldoacauan** [comment]
@fdaciuk Concordo que muitas labels gera bagunca, mas ali labels (que nao sao complementares como priority e os status) são apenas 8 :P

**Comment by fdaciuk** [comment]
@oswaldoacauan Exato! Ae juntando suggestion, enhancement e feature em uma só já ficamos com 2 a menos o/ 

xD

**Comment by oswaldoacauan** [comment]
@fdaciuk Como eu disse acima, são coisas totalmente diferentes, portanto nao devem ser tratadas igualmente.

Uma Suggestion da comunidade nem sempre é uma nova Feature ou uma Melhoria, pode ser uma mudança de estilo, paradigma, componente. Quem deu a sugestão obviamente considera uma melhoria para o projeto, mas o resto da comunidade pode achar o contrario, portanto é caracterizado como uma sugestão antes de virar uma feature ou melhoria.

**Comment by fdaciuk** [comment]
Pois é.. entendo.. mas a questão é se todas essas labels serão mesmo usadas xD

Deixando poucas (ainda que no início do projeto), já diminuiria bastante a categorização. Depois, conforme a necessidade, poderia ir adicionando mais :)

Não que eu não tenha gostado da sua organização. Pelo contrário: achei tudo muito bem definido. Mas acho que inicialmente poderíamos começar com umas 4 ou 5 no máximo, partindo do princípio K.I.S.S xD

**Comment by luanmuniz** [comment]
Uma sugestão sempre vai ser para melhorar. Uma melhoria não necessariamente é uma nova feature mas uma nova feature necessariamente é uma melhoria hehehe. Para mim não tem necessidade de ter essa separação.

Pensei também sobre as labels de prioridade e de status. Sobre as labels de status, esse projeto é comunitário, não tem uma equipe onde o usuário x irá cuidar do issue y etc. A comunidade em si irá fazer a manutenção. Tendo em vista que somente os administradores do repo podem inserir labels nas issues é inviável colocar esse tipo de responsabilidade na mão de uma equipe pequena de administradores. Sem contar que não da para saber se um issue está "em andamento" ou "parado", um usuário comentar no issue que está resolvendo, não significa nada.

Sobre as labels de prioridade, quem irá definir se uma issue é mais importante que o outra, não da para deixar isso na mão da comunidade porque gera conflito. Além do que, novamente, este projeto é comunitário, cada um pode escolher com o que irá contribuir, logo, por mais que uma issue de segurança esteja com label de alta prioridade, as pessoas podem simplesmente decidir ignorar, e fazer uma melhoria na fonte do titulo de login. Acho que uma alternativa para as labels de prioridade é uma label de "Important". Assim conseguimos destacar o que merece atenção especial.

**Comment by oswaldoacauan** [comment]
@luanmuniz Uma sugestao pode ser uma melhoria para o caso de quem sugeriu, mas não para o todo. Exatamente por uma melhoria nao ser uma feature que precisa-se dessa divisão,

As labels de status acho legal manter, até porque nao precisa-se necessariamente usa-las em todas issues, só nas mais "importantes" ou mais "criticas" para a comunidade saber qual o status dela.

:+1: para ter apenas um label "Important".

PS. Legal ver que em uma coisa relativamente simples e básica como as labels, já ta tendo uma discussão monstra, espero que continue assim quando chegar pontos mais críticos do projeto :smile_cat:

**Comment by chrisenytc** [comment]
:+1: Para apenas uma label "Important"

**Comment by luanmuniz** [comment]
As Labels de status acabaram ficando por conta do Waffle, então nem precisamos mais discutir elas.
Única coisa que entramos em um impasse então é se suggestion, enhancement e feature devem ser 3 labels separadas ou se será uma só "Enhacement" ou algum outro nome que represente as 3 em uma só. 

Se formos usar uma só representando as 3 acho que podemos fazer a seguinte estrutura:
- Enhacement (Para sugestões, melhorias, novas funcionalidades etc)
- Bug (Para Bugs. obvio)
- Documentation (Para qualquer coisa relacionada a documentação)
- Performance problem (Para problemas de perfomance)
- Security problem (Para problemas de segurança)
- Design (Para qualquer coisa relacionada a design)
- Third Parts (Para problemas com dependências ou com partes de terceiros)

Para Labels de status
- Important (Para marcação de assuntos importantes)
- Awaiting feedback (Para qualquer coisa que esteja aguardando feedback)

@fdaciuk se manisfestou preferindo uma só, eu também prefiro uma só. Pessoal, qual é a opinião de vocês? Acham que devemos adicionar alguma às opções acima, retirar alguma?

**Comment by oswaldoacauan** [comment]
@luanmuniz 
Ainda nao concordo que devemos juntar as três labels, suggestion e enhancement até pode-se pensar, agora juntar feature nessa salada de fruta ai sou totalmente contra.

E awaiting feedback não equivale ao "backlog" do waffle?

**Comment by chrisenytc** [comment]
Nessa parte concordo com você @oswaldoacauan, Eu deixaria feature fora da lista como uma label separada. :+1:

**Comment by luanmuniz** [comment]
@oswaldoacauan Sim, realmente Awaiting Feedback é equivalente ao backlog, não é exatamente a mesma coisa, mas se encaixa.

@chrisenytc @oswaldoacauan  Vocês acham que podemos manter a estrutura acima tirando o Feedback e adicionando um New Feature então?

**Comment by oswaldoacauan** [comment]
Só Feature, sem new.

Em 5 de outubro de 2013 14:51, Luan Muniz notifications@github.comescreveu:

**Comment by chrisenytc** [comment]
Só Feature :+1:

**Comment by luanmuniz** [comment]
Acho que chegamos a um acordo então, estou fechando a issue, se alguém tiver mais alguma consideração, pode reabrir!
