### ISSUE TITLE
Vakinha para o dominio

### ISSUE THREAD

**Issue by luanmuniz** [NodeJS-Brasil/brazi.la#6]
Fala galera!!
Estamos arrecadando dinheiro para comprar o dominio .la do brazi!
O Braz.la foi concebido e está sendo desenvolvido pela comunidade brasileira de Node.js.

O projeto está sendo 100% colaborativo, então achamos justo a comunidade contribuir também para a compra do domínio!! O dominio .la custa $50, o que atualmente da R$ 111,34, porem colocamos 140 para cobrir as taxas que teremos na hora de converter e de pagar a vakinha.com.br 

http://www.vakinha.com.br/VaquinhaP.aspx?e=220797

**Comment by caarlos0** [comment]
paypal?

**Comment by luanmuniz** [comment]
A vakinha está no meu nome.
Adiciona aqui de quanto foi a sua contribuição que ai somo aqui com as que já tem, assim não fica dinheiro a mais comigo.

**Comment by caarlos0** [comment]
Beleza, transferi 15 dilmas pra tua conta =)

**Comment by oswaldoacauan** [comment]
Coloquei 10dilmas na vakinha

**Comment by chrisenytc** [comment]
@luanmuniz não sou mt fã desse site, haha e meu cartão está bloqueado ai lembrei que tinha sobrado uns trocados  lá no paypal e mandei pra teu paypal 4,5 reals ;)

**Comment by fabiorogeriosj** [comment]
opa @luanmuniz, contribui com 40!

**Comment by mateusavila** [comment]
paypal?

**Comment by caarlos0** [comment]
@mateusavila olha o começo da thread

**Comment by diogobeda** [comment]
Mandei 15 HUE BR lá :)

**Comment by hugofcampos** [comment]
10 pila
