### ISSUE TITLE
Criação do logo

### ISSUE THREAD

**Issue by luanmuniz** [NodeJS-Brasil/brazi.la#7]
Designers?

**Comment by mateusavila** [comment]
O grupo do Paraná JS teve um maluco que criou altas logo para a comu lá no face. O suissa poderia entrar em contato.

**Comment by suissa** [comment]
Opa demoro!

**Comment by mateusavila** [comment]
Era o BOB Marley, digo Marlon que criou. O cara é fera!

**Comment by vitorbritto** [comment]
Vou fazer umas brincadeiras com o nome. =]

**Comment by luanmuniz** [comment]
Podemos usar o mascote como logo mesmo, o que acham?

**Comment by gustavohenke** [comment]
É uma boa, @luanmuniz.

**Comment by chrisenytc** [comment]
É massa assim não tem 2 trabalhos.

**Comment by BobMarlonPDT** [comment]
Amanhã a tarde acho que tento criar alguma coisa utilizando alguns elementos discutidos no mascote e vou tentar criar algo por conta tbm, Assim que fizer, mando pra vcs olharem. =D

**Comment by fabiorogeriosj** [comment]
![brazila-logo](https://f.cloud.github.com/assets/1442874/1994126/e61f0f7c-84e6-11e3-96ff-0ace9b51dcc2.png)

Sugestão de logo! Aguem tem ideia de um slogan melhor?

Também pode ser visto a logo aplicada no layout:

https://redpen.io/uk9afg

O que acham?

**Comment by suissa** [comment]
Eu curti!

2014-01-24 Fábio Rogério SJ notifications@github.com

> [image: brazila-logo]https://f.cloud.github.com/assets/1442874/1994126/e61f0f7c-84e6-11e3-96ff-0ace9b51dcc2.png
> 
> Sugestão de logo! Aguem tem ideia de um slogan melhor?
> 
> Também pode ser visto a logo aplicada no layout:
> 
> https://redpen.io/uk9afg
> 
> O que acham?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NodeJS-Brasil/brazi.la/issues/7#issuecomment-33214275
> .

## 

_Jean C. Nascimento aka Suissa_
Organizador Sampa.js, FrontinSampa, FrotinPG
NoSQL e JS/Node.js Evangelist

CIO - MeGaranto
CEO - Suissa Corp

http://nodeware.com.br_Suissa Corp_
Consultoria, Treinamento e Cursos em HTML5, CSS3, Javascript, jQuery,
AngularJs, Node.js e MongoDb

http://about.me/suissa
http://www.linkedin.com/profile/view?id=46505642
http://www.facebook.com/suissa
  http://twitter.com/suissacorp  http://www.delicious.com/suissa
jnascimento@gmail.com

**Comment by gustavohenke** [comment]
@fabiorogeriosj "made **with** love"?

**Comment by matheuslc** [comment]
curti made with love não. Na minha opinião ficaria melhor apensas " A fresh new CMS"

**Comment by oswaldoacauan** [comment]
@gustavohenke é faltou o with :p

Tambem nao achei muito legal esse **_made with love**_.

Que tal **_Just a CMS plataform.**_ ~~badumtss~~
