### ISSUE TITLE
Criação de um Mascote

### ISSUE THREAD

**Issue by chrisenytc** [NodeJS-Brasil/brazi.la#8]
O Projeto vai ter um mascote? A maioria dos projetos open-source tem um mascote como o Bower, Grunt, GtiHub, OctoPress e outros. Vocês acham válido ter um? Se sim, há alguém que se habilite a fazer um ao longo do projeto?

**Comment by luanmuniz** [comment]
:+1:
Não sou designer nem ilustrador, mas apoio a ideia xD

**Comment by iamfelipemattos** [comment]
eu gostaria de participar desse projeto mas não tenho conhecimento algum em
nodejs, tem algum problema?

ps: mas posso aprender.

Att, Felipe Souza.

2013/10/1 Luan Muniz notifications@github.com

**Comment by chrisenytc** [comment]
@IAMFELIPESOUZA Você não precisa necessariamente saber Node.Js temos vários grupos de desenvolvimento, entre no grupo e escolha um. Tem Front-End, Designer, Modelagem de Banco de Dados e etc. Entre em nosso grupo. https://www.facebook.com/groups/brazi.la/

**Comment by nicholasess** [comment]
O que nós podemos fazer é desenhar no papel um mascote, fazemos uma votação e algum ilustrator passa para png/svg e etc

**Comment by suissa** [comment]
Um tatu bola ou uma onça pintada ou uma papaguaio (louro) ia ser maneiro hein :D

Mas podemos pensar conceitualmente em algo como uma formiga pois como sabemos elas todas tem seu papel bem definido (single responsability) e todas trabalham para o bem comum, assim como será nosso sistema.

http://economia.estadao.com.br/noticias/economia-geral,formiga-maluca-brasileira-invade-eua-e-provoca-apagoes,156062,0.htm
LOL

**Comment by chrisenytc** [comment]
A ideia da formiga é interessante ou uma abelha também. hahaha :+1:

**Comment by oswaldoacauan** [comment]
Curti a da formiga :+1:

**Comment by fdaciuk** [comment]
+1 pra formiga xD

**Comment by suissa** [comment]
Se for abelha daria para fazer a bundinha dela em vez de amarelo e preta, amarelo e verde :8ball:

**Comment by caarlos0** [comment]
+1 formiga

**Comment by suissa** [comment]
Achei uma abelha http://www.freepik.com/free-vector/vector-bee-for-business-logo-or-icons_557720.htm

**Comment by suissa** [comment]
Inspiração para formiga http://designinspector.com/30-adorable-ant-logos-for-your-inspiration/

**Comment by suissa** [comment]
Abelha base http://dribbble.s3.amazonaws.com/users/108671/screenshots/471927/bee2.jpg

**Comment by suissa** [comment]
Ant Vector http://cdn.vectorstock.com/i/composite/23,43/outlined-ant-vector-272343.jpg

**Comment by diogobeda** [comment]
Hahahaha, curti muito essa idéia da formiga. +1

**Comment by oswaldoacauan** [comment]
![Formiguxa](http://designinspector.com/wp-content/uploads/2013/07/6-construction-yellow-ant-logo.jpg)

Essa ta foda.

**Comment by diogobeda** [comment]
Talvez uma referência a Alien Ant Farm? :P
http://fc09.deviantart.net/fs6/i/2005/052/b/d/Alien_Ant_farm__Anthology_Logo_by_Mordaqui.png

**Comment by brunosalgueiro** [comment]
Eu mandaria algum dos maiores representantes do Brasil, Blanka ou Zé Carioca, sem mais!

**Comment by luanmuniz** [comment]
Blanka ou Zé carioca :+1:

**Comment by fdaciuk** [comment]
Blanka ou Zé Carioca seria massa! Mas acho que vamos ter problema com o "copie direito" =\

**Comment by nicholasess** [comment]
+1 formiga, abelha fica muito gay '-'

**Comment by iamfelipemattos** [comment]
+1 formiga e a savant é magnifica rs.

**Comment by suissa** [comment]
Um Blanka estilizado ia ser foda hein!

**Comment by brunosalgueiro** [comment]
Se Street Fighter ainda estivesse gerando algum dinheiro, e se alguém ficar indignado com o lucro do nosso projeto open source rs. Nesse caso poderíamos ter problemas com direitos de imagem. 
Eu voto pelo Blanka pois esse mascote faria um baita sucesso na comunidade, só que precisamos de um bom designer disposto a desenhar.

**Comment by chrisenytc** [comment]
Acho que seria melhor a formiga pois seria direito nosso e criado pela comunidade.

**Comment by oswaldoacauan** [comment]
Não gostei da ideia do blanka :p

É tipo por o HUEBoy de mascote.

Em 3 de outubro de 2013 18:16, Bruno Salgueiro
notifications@github.comescreveu:

**Comment by luanmuniz** [comment]
HUEBoy! :+1: uhaeuhaeuhaeuhea
Brincadeiras a parte, o conceito da formiga é bem maneiro mesmo, acho que podemos usar ela, mas usar alguma pronta acho que não seria legal.
Temos designers ou ilustradores no projeto? A Galera podia tentar recrutar alguns em! Vamos precisar para desenhar o painel administrativo também :D

**Comment by chrisenytc** [comment]
A formiga tem que ser desenhada do zero para ser a representante do projeto. Ficaria muito mais legal. :+1:

**Comment by oswaldoacauan** [comment]
Sim, só postei aquela pq achei a ilustraçao muito maneira :D

**Comment by iamfelipemattos** [comment]
o que acham?
![untitled-1](https://f.cloud.github.com/assets/5552126/1276970/9c065e18-2ea1-11e3-8d51-d087a0650297.jpg)

**Comment by caarlos0** [comment]
eu curti!

On Sun, Oct 6, 2013 at 1:09 PM, Felipe Souza notifications@github.comwrote:

> o que acham?
> [image: untitled-1]https://f.cloud.github.com/assets/5552126/1276970/9c065e18-2ea1-11e3-8d51-d087a0650297.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NodeJS-Brasil/brazi.la/issues/8#issuecomment-25770811
> .

## 

Best regards,
_Carlos Alexandro Becker_
http://carlosbecker.com/about

**Comment by iamfelipemattos** [comment]
@suissa o que acha dessa?
![logo](https://f.cloud.github.com/assets/5552126/1278483/827a74be-2f16-11e3-9368-518cfafb5945.jpg)

**Comment by gustavohenke** [comment]
Muito bom! :+1:

**Comment by luanmuniz** [comment]
@IAMFELIPESOUZA Você que fez essas ilustrações? O_o

**Comment by matheuslc** [comment]
Curti também!

**Comment by fdaciuk** [comment]
Ficou da hora mesmo! Se foi o @IAMFELIPESOUZA que fez, o bicho é fera xD

**Comment by suissa** [comment]
Caraleo que foda esses 2, essa raposa ficou legal, vc mesmo que desenhou @IAMFELIPESOUZA  ?

**Comment by oswaldoacauan** [comment]
Não foi o @IAMFELIPESOUZA que fez não.

http://j3concepts.deviantart.com/art/Tee-Total-Clothing-Fox-317978876

http://www.redbubble.com/people/cronobreaker/works/9477285-mind-your-own-beeswax

**Comment by fabiorogeriosj** [comment]
Vou dar uma brincada com a ideia da formiga!

**Comment by fabiorogeriosj** [comment]
Segue um protótipo!

Como não sou ilustrador, apenas peguei um brush para photoshop e dei uns pitecos!

Talvez alterar cor, estilo, sem degrade ou jogar fora ksksksk!

![brazila1](https://f.cloud.github.com/assets/1442874/1289734/4642e60a-3026-11e3-8d9a-1000e4a3754c.png)

**Comment by caarlos0** [comment]
CURTI MUITO O DA FORMIGA CARA

2013/10/8 Fábio Rogério SJ notifications@github.com

> Segue um protótipo!
> 
> Como não sou ilustrador, apenas peguei um brush para photoshop e dei uns
> pitecos!
> 
> Talvez alterar cor, estilo, sem degrade ou jogar fora ksksksk!
> 
> [image: logo1]https://f.cloud.github.com/assets/1442874/1289717/e14689b4-3025-11e3-9371-4d0460fc580c.JPG
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NodeJS-Brasil/brazi.la/issues/8#issuecomment-25894723
> .

## 

Best regards,
_Carlos Alexandro Becker_
http://carlosbecker.com/about

**Comment by chrisenytc** [comment]
@fabiorogeriosj Ficou legal.. :)

**Comment by diogobeda** [comment]
@fabiorogeriosj  Tbm curti pra caramba

**Comment by fabiorogeriosj** [comment]
Da pra ir brincando com o mascote!

Talvez assim:

![brazila2](https://f.cloud.github.com/assets/1442874/1290252/957f67aa-302d-11e3-97e4-e6cba0bf3f0d.png)

**Comment by gustavohenke** [comment]
Tá ficando maneiro :)

**Comment by vitorbritto** [comment]
A ideia inicial está bacana! Mas, poderíamos deixá-la mais "zangada". =]

**Comment by alexsandro-xpt** [comment]
Gostei da primeira logo da formiga.

**Comment by fabiorogeriosj** [comment]
Não entendi o porque de deixar ela zangada mais ta ai:

![brazila3](https://f.cloud.github.com/assets/1442874/1290512/ada79d12-3031-11e3-853c-3bfc074b7f83.png)

**Comment by iamfelipemattos** [comment]
opa galera desculpa demora, então sobre as ilustrações não foi eu não, eu nem manjo design rs, é apenas algumas imagens que curti e achei que ficaria legal e queria compartilhar com vocês.

**Comment by mateusavila** [comment]
Formiguinha feliz é 1000 vezes mais legal. Essa coisa de ficar vendo Jaspion e achar que raivoso é legal é do tempo que o Maujor era adolescente.

**Comment by fabiorogeriosj** [comment]
hehehe, concordo com o @mateusavila!

No meu olhar de designer prefiro a primeira opção!

**Comment by suissa** [comment]
Votem ai galera, malvada ou boazinha? Também achei a boazinha mais "bonita"

**Comment by chrisenytc** [comment]
:+1: pra primeira

**Comment by oswaldoacauan** [comment]
Gostei mais da boazinha, mas acho que ia ficar mais legal ela "olhando" pro usuario, ou seja, olhando para frente

**Comment by fabiorogeriosj** [comment]
Leval @oswaldoacauan  Segue olhando para frente para comparação:

![brazila5](https://f.cloud.github.com/assets/1442874/1292467/d88a22ca-3054-11e3-86f2-0fb17e61f9f6.png)

**Comment by fabiorogeriosj** [comment]
E assim fica feliz de mais?

![brazila6](https://f.cloud.github.com/assets/1442874/1292516/b644c96c-3055-11e3-9767-e427e55dd821.png)

**Comment by oswaldoacauan** [comment]
@fabiorogeriosj Ela parece estar apavorada huAUHEAUHEHUAE, gostei mais da segunda

Eu tinha imaginado ela em outro angulo, procurei umas no deviantart olhando para "frente"

http://itsjustin.deviantart.com/art/Charlie-Ant-275615553
http://venkman-project.deviantart.com/art/Enthusiastic-Ant-271009645
http://lunar-maniac.deviantart.com/art/Ant-278463330
http://m0ntenegr0.deviantart.com/art/ANTS-257029705
http://minishkou.deviantart.com/art/Ant-375504511
http://sr-manicomio.deviantart.com/art/ant-tontita-15189702

**Comment by fabiorogeriosj** [comment]
@oswaldoacauan agora entendi!

Vou dar uma brincada e ver o que sai...

**Comment by BobMarlonPDT** [comment]
![morfiga](https://f.cloud.github.com/assets/5642606/1301980/453ba3ea-312b-11e3-929d-7651f9b4e9ba.jpg)
To brincando tbm. =D

**Comment by chrisenytc** [comment]
@BobMarlonPDT Eu gostei dessa que você fez. :+1:

**Comment by vitorbritto** [comment]
Não tão zangada! Hahahahaha!

Talvez não tenha me expressado bem, mas achei muito infantil o mascote. Não me passou firmeza. Vou procurar algumas referências e publico aqui. =]

**Comment by vitorbritto** [comment]
A melhor imagem como referência que encontrei foi da Formiga Atômica.

Percebam que a expressão dela demonstra **determinação**, **força** e **firmeza**. Foi o que quis passar com o "zangada".

![hb_color_page_atom_ant_by_slappy427-730881](https://f.cloud.github.com/assets/769193/1316610/ca439f4c-3299-11e3-8fa3-d8b10a48ad26.jpg)

**Comment by oswaldoacauan** [comment]
Pode-se notar tambem que ela está ajudando do Goku a fazer a Genkidama x)

Mas concordo com o Vitor, acho que da pra fazer algo bonito e clean
passando "confiança".

Em 11 de outubro de 2013 14:24, Vitor Britto notifications@github.comescreveu:
