### ISSUE TITLE
Usar waffle.io?

### ISSUE THREAD

**Issue by matheuslc** [NodeJS-Brasil/brazi.la#9]
Galera, estamos usando o trello, mas já que não começamos popular ainda, podemos migrar para o Waffle. Ele ja faz a integração com o GitHub. E ai, vamos?

https://waffle.io/

**Comment by chrisenytc** [comment]
:+1: Eu apoio. Gostei da ideia..

**Comment by oswaldoacauan** [comment]
:+1: não conhecia e achei bacana

**Comment by suissa** [comment]
Integrei ja https://waffle.io/NodeJS-Brasil/brazi.la

**Comment by fdaciuk** [comment]
Também não conhecia.. bem legal! xD

**Comment by diogobeda** [comment]
Porra cara, muito bom. Não conhecia tbm, vou até usar em outro projeto :D

**Comment by suissa** [comment]
Nem eu conhecia :+1:
